import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,}: Readonly<{children: React.ReactNode;}>) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
          
          min-h-screen flex flex-col items-center justify-start p-20 gap-2
          `} 
      >

        <header className="flex flex-col items-center">
          <h1>O Meu Site</h1>

          <nav className="flex gap-4">
            <Link href="/" className="hover:underline">Home</Link>
            <Link href="/sobre" className="hover:underline">Sobre</Link>
            <Link href="/tecnologias" className="hover:underline">Tecnologias</Link>
            <Link href="/jokes" className="hover:underline">Jokes</Link>
      
          </nav>

        </header>

        <main className="bg-blue-200 p-5 rounded-2xl min-h-[70vh] 
                          w-full md:w-2/3 lg:w-1/2 xl:w-1/3">
          {children}
        </main>
        
        <footer>
          DIW
        </footer>

      </body>
    </html>
  );
}